### PR TITLE
make src/services/api.service.ts work with https servers requiring client certificates

### PR DESCRIPTION
**Pull request by yxzzx**
Tested with firefox 52.7.3ESR

### CODE REVIEW

**Comment by kspearrin** [comment]
I am a little confused as to what this allows? What kind of credentials are being sent with these requests?

**Comment by yxzzx** [comment]
My apache webserver is configured with:
`
SSLCACertificateFile ".../client-ca.pem"
SSLVerifyClient require
`
With this configuration the browser has to present a user certificate from its certificate store issued by a specific CA requested by the webserver. 
Without the proposed changes bitwarden will present the certificate only with chrome but not with firefox. Because of this the initial SSL-handshake will fail with firefox and access to the vault will not be granted.

**Comment by kspearrin** [comment]
IS there a reason you closed this?

**Comment by yxzzx** [comment]
Sorry, pressed wrong button :-( and didn't notice.

**Comment by kspearrin** [comment]
Is this still needed now that ESR is @ Firefox 60?

**Comment by yxzzx** [comment]
Doesn't work with firefox 60. BTW, it also doesn't work with edge (I just tried). Probably it doesn't work for anything but chrome. From what I have read, chrome does things different to the standard.

**Pull request merged**
