### PR TITLE
Bumping electron version 14.1.1

### PR DESCRIPTION
**Pull request by joseph-flinn**
## Type of change
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [x] Other

## Objective
Updating electron by a minor version

## Code changes
- **package.json: ** version bump of electron

## Testing requirements
- Regression testing needed to make sure everything still operates as expected.

### CODE REVIEW

**Review by justindbaur — APPROVED** [review]

**Review by Hinton — CHANGES_REQUESTED** [review]
We need to bump `package-lock.json` for all `package.json` changes.

**Comment by Hinton** [comment]
Version 14.1.1 seems to be the latest, any specific reason we didn't upgrade to that?

**Comment by Hinton** [comment]
@joseph-flinn We need to also bump the `package-lock.json` inside `electron`.

**Comment by djsmith85** [comment]
Closing this as update will be done by https://github.com/bitwarden/jslib/pull/534

**Pull request closed without merging**
