### PR TITLE
Global history

### PR DESCRIPTION
**Pull request by ajayyy**
This adds global edit history to notes and passwords.

Today I decided to try switching to Bitwarden from LastPass. It worked out well, but I was really missing this one feature.

This method only requires changing this library's code and does not require any server changes. It simply adds the item type to the saved item. I can prepare a client side PR as well to change the text to say "Edit History" instead of "Password History". 

image

Resolves https://github.com/bitwarden/server/issues/33

### CODE REVIEW

**Comment by kspearrin** [comment]
This feature was built to store password history. It's a bit of a hack to change it as-is to store other type of data.

**Comment by ajayyy** [comment]
I did it this way due to not being super familiar with the code-base yet, but I can make a full update if you would like. Which way do you think would be best:

1. Add a `type` variable to the current `PasswordHistory` endpoint
2. Make a new endpoint for this with a `type` variable

**Comment by ajayyy** [comment]
@DanStevens Password history should work fine, this one just extends the password history to work with all fields (notes, etc.).

I personally use my fork with this change and it has been working great for me, but I understand why Bitwarden would want a complete rewrite that used a new history mechanism instead of prepending the `Field name: ` in front of the values that aren't passwords inside the normal password history.

**Comment by Hinton** [comment]
Hi,

We are currently in the process of archiving this repository and moving the code and future development to the [bitwarden/clients](https://github.com/bitwarden/clients) repository. This PR will be closed but feel free to re-open it again on [bitwarden/clients](https://github.com/bitwarden/clients).

**Pull request closed without merging**
