### PR TITLE
[ps-136] Moved normalizeSearchQuery method to Utils

### PR DESCRIPTION
**Pull request by gbubemismith**
## Type of change

- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Code changes
- **common/src/services/search.service.ts:** referenced utils class and changed normalizeSearchQuery call to use the utils method.

- **common/src/misc/utils.ts:** moved `normalizeSearchQuery` here so it can be accessed by `lunr` pipeline function.

 

## Before you submit

- [X] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

### CODE REVIEW

**Comment by Hinton** [comment]
Wasn't this already merged in #812?

**Comment by Hinton** [comment]
We could just a private internal function in the file and use it?

**Comment by gbubemismith** [comment]
> 

do you mean like a private normalizeQuery function and then call the function with `this.normalizeQuery` in the pipeline function???

**Comment by Hinton** [comment]
Yes, just moving `normalizeQuery` to be a top level function. That should keep it accessible in the lunr pipeline (or so I assume).

**Comment by gbubemismith** [comment]
> Yes, just moving `normalizeQuery` to be a top level function. That should keep it accessible in the lunr pipeline (or so I assume).

Moved it to the utils class

**Review by eliykat — COMMENTED** [review]
`Utils` is a bit of a miscellaneous class, we shouldn't add to it if we can avoid it.

I would recommend just making `normalizeSearchQuery` a public method on `SearchService`, will that work for lunr? Or if it needs to be static, make it static on `SearchService`. You can do either without moving it to `Utils`.

@Hinton I don't quite understand your feedback, is this what you were suggesting?

**Comment by gbubemismith** [comment]
> `Utils` is a bit of a miscellaneous class, we shouldn't add to it if we can avoid it.
> 
> I would recommend just making `normalizeSearchQuery` a public method on `SearchService`, will that work for lunr? Or if it needs to be static, make it static on `SearchService`. You can do either without moving it to `Utils`.
> 
> @Hinton I don't quite understand your feedback, is this what you were suggesting?

made it a static method in `SearchService`

**Comment by Hinton** [comment]
@eliykat I'm fine with static on SearchService. My initial thought was to create a function outside the class and call it. Javascript isn't locked to OOO and we can diverge if needed.

**Review by differsthecat — APPROVED** [review]
This looks good 👍

**Pull request merged**
